# Generated by Django 3.0.5 on 2020-05-22 17:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20200522_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3)])),
                ('reviewer', models.PositiveIntegerField()),
                ('entry_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalTrophies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophies', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
