# Generated by Django 3.0.5 on 2020-05-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20200522_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltrophies',
            name='entry_id',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
