# Generated by Django 3.0.5 on 2020-04-27 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20200427_0507'),
        ('accounts', '0005_auto_20200427_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='profile1.png', upload_to='images/products')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('product_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ServiceLevel')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='accounts.Tag')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
