# Generated by Django 3.0.5 on 2020-05-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='challenge',
        ),
    ]
