# Generated by Django 3.0.5 on 2020-05-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_challenge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='file',
            new_name='image_file',
        ),
    ]
