# Generated by Django 3.0.5 on 2020-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20200517_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/image/'),
        ),
    ]
