# Generated by Django 3.0.5 on 2020-05-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
