# Generated by Django 3.0.5 on 2020-05-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20200522_0742'),
        ('submissions', '0008_entry_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ratings',
            field=models.ManyToManyField(to='ratings.Rating'),
        ),
    ]
