# Generated by Django 3.0.5 on 2020-04-29 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField(max_length=1000)),
                ('example_image', models.ImageField(blank=True, null=True, upload_to='challenges/videos')),
                ('example_video', models.FileField(blank=True, null=True, upload_to='challenges/videos')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('member_limit', models.PositiveIntegerField()),
                ('video_time_limit', models.PositiveIntegerField()),
                ('submission_storage_cap', models.PositiveIntegerField()),
                ('submission_types', multiselectfield.db.fields.MultiSelectField(choices=[('iamge', 'Image'), ('audio', 'audio'), ('video', 'video')], max_length=17)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
