# Generated by Django 3.0.5 on 2020-05-09 19:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20200509_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='submission_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('image', 'Image'), ('audio', 'audio'), ('video', 'video')], max_length=17),
        ),
    ]
