# Generated by Django 3.0.5 on 2020-05-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_member_challenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='example_image',
            field=models.ImageField(default='https://mmh-challenger.s3.us-east-2.amazonaws.com/media/challenges/images/American-Gothic_House.jpg', upload_to='challenges/images'),
            preserve_default=False,
        ),
    ]
