# Generated by Django 3.0.5 on 2020-05-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_remove_submission_challenge'),
        ('challenges', '0006_auto_20200516_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='submissions',
            field=models.ManyToManyField(to='submissions.Submission'),
        ),
    ]
