# Generated by Django 3.0.5 on 2020-05-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_challenge_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='submissions',
        ),
    ]
