# Generated by Django 3.0.5 on 2020-05-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_challenge_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
