# Generated by Django 3.0.5 on 2020-05-28 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_auto_20200527_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 5, 27)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 5, 27)),
        ),
    ]
