# Generated by Django 3.0.5 on 2020-05-28 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_auto_20200527_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 20, 48, 34, 18773)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 20, 48, 34, 18752)),
        ),
    ]
