# Generated by Django 3.0.5 on 2020-05-30 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0014_auto_20200527_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 12, 31, 44, 43331)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 12, 31, 44, 43304)),
        ),
    ]
