# Generated by Django 3.0.5 on 2020-05-30 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_auto_20200530_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 12, 39, 45, 453704)),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 30, 12, 39, 45, 453674)),
        ),
    ]
