# Generated by Django 3.0.5 on 2020-04-27 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200427_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelevel',
            name='max_members_per_challenge',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicelevel',
            name='max_number_of_challengers',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicelevel',
            name='max_submission_size_in_MB',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicelevel',
            name='video_length_in_seconds',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicelevel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/products'),
        ),
    ]
