# Generated by Django 3.0.5 on 2020-05-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200427_0507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicelevel',
            old_name='max_number_of_challengers',
            new_name='max_number_of_challenges',
        ),
    ]
